#!/usr/bin/with-contenv bash

exec \
	s6-setuidgid abc python /app/headphones/Headphones.py -p 8181 \
	--datadir=/config --db_host=postgres --db_name=headphones --db_user=headphones --db_pass=headphones --verbose
